version: 2.1

commands:

workflows:
  version: 2

  build-test-flow:
    jobs:
      - make-archives

      - make-test-browser:
          requires:
            - make-archives

      - make-test-8-4-static:
          requires:
            - make-archives
      - make-test-8-4-shared:
          requires:
            - make-archives
      - make-test-8-4-dynamic:
          requires:
            - make-archives

      - make-test-8-3-static:
          requires:
            - make-archives
      - make-test-8-3-shared:
          requires:
            - make-archives
      - make-test-8-3-dynamic:
          requires:
            - make-archives

      - make-test-8-2-static:
          requires:
            - make-archives
      - make-test-8-2-shared:
          requires:
            - make-archives
      - make-test-8-2-dynamic:
          requires:
            - make-archives

      - make-test-8-1-static:
          requires:
            - make-archives
      - make-test-8-1-shared:
          requires:
            - make-archives
      - make-test-8-1-dynamic:
          requires:
            - make-archives

      - make-test-8-0-static:
          requires:
            - make-archives
      - make-test-8-0-shared:
          requires:
            - make-archives
      - make-test-8-0-dynamic:
          requires:
            - make-archives

jobs:

  make-archives:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - checkout
      - run: npm install
      - run: cp .circleci/.env_8.3.ci .env
      - run: time make archives
      - persist_to_workspace:
          root: ~/
          paths:
            - project/

  make-test-browser:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.3.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: npm install
      - run: npm i -g cv3-test netcat
      - run: sudo apt update && sudo apt install docker-compose -y
      - run: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - run: sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
      - run: sudo apt-get update
      - run: sudo apt install -y software-properties-common google-chrome-stable
      - run: cd demo-web; ./switch-packages.sh local; cd ..;
      - run: cp .circleci/.env_8.3-dynamic.ci .env
      - run: make image
      - run: make web-mjs worker-cgi-mjs web-dbg-mjs
      - run: test/browser-test.sh

  make-test-8-4-static:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.4.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-4-shared:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.4-shared.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-4-dynamic:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.4-dynamic.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-3-static:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.4.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-3-shared:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.3-shared.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-3-dynamic:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.3-dynamic.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-2-static:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
            at: ~/
      - run: cp .circleci/.env_8.2.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-2-shared:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.2-shared.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-2-dynamic:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.2-dynamic.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-1-static:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
            at: ~/
      - run: cp .circleci/.env_8.1.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-1-shared:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.1-shared.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-1-dynamic:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.1-dynamic.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-0-static:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
            at: ~/
      - run: cp .circleci/.env_8.0.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-0-shared:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.0-shared.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test

  make-test-8-0-dynamic:
    parallelism: 1
    machine:
      image: ubuntu-2204:2024.05.1
    resource_class: medium
    steps:
      - attach_workspace:
          at: ~/
      - run: cp .circleci/.env_8.0-dynamic.ci .env
      - run: find . -type f -name "*.a" -exec touch {} +
      - run: time make test
